package TYPES;

public enum TypeEnum
{
    TYPE_VAR,
    TYPE_ARRAY,
    TYPE_CLASS,
    TYPE_CLASS_VAR_DEC,
    TYPE_CLASS_VAR_DEC_LIST,
    TYPE_FOR_SCOPE_BOUNDARIES,
    TYPE_FUNCTION,
    TYPE_INT,
    TYPE_LIST,
    TYPE_NIL,
    TYPE_STRING,
    TYPE_VOID
}